// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

const basepath = 'src/infrastructure/persistence/prisma/';
export default defineConfig({
    schema: `${basepath}schema.prisma`,
    migrations: {
        path: `${basepath}migrations`,
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});
